"""Add avatar_url to User model

Revision ID: 66535b2e3047
Revises: cd88f778a1cc
Create Date: 2025-11-20 00:44:58.136668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66535b2e3047'
down_revision = 'cd88f778a1cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###
