"""Initial migration on MySQL

Revision ID: aa878faf6283
Revises: 
Create Date: 2025-11-19 23:47:12.942345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa878faf6283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_slip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_slip_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_slip_created_at'), ['created_at'], unique=False)

    op.create_table('import_slip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_slip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_slip_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_slip_created_at'), ['created_at'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_in_stock', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_name'), ['name'], unique=True)

    op.create_table('export_slip_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('export_price', sa.Float(), nullable=True),
    sa.Column('export_slip_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['export_slip_id'], ['export_slip.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_slip_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('import_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('import_slip_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_slip_id'], ['import_slip.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_slip_detail')
    op.drop_table('export_slip_detail')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_name'))

    op.drop_table('product')
    with op.batch_alter_table('import_slip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_slip_created_at'))
        batch_op.drop_index(batch_op.f('ix_import_slip_code'))

    op.drop_table('import_slip')
    with op.batch_alter_table('export_slip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_slip_created_at'))
        batch_op.drop_index(batch_op.f('ix_export_slip_code'))

    op.drop_table('export_slip')
    # ### end Alembic commands ###
